import '../App';
import {Container,Row,Col,Table,} from 'react-bootstrap';
import '../Another_Page_Css/Attribute.css';
import React from 'react';
import p8 from '../image/8.gif';
import G7 from '../image/G7.gif';
import G12 from '../image/G12.gif';
  function Attribute(){
    

	return(
		<div className='a'>
      <br />
      <br />
      <br />
      <div className='a'>

      
			<h1 className='text7'>
        <img src={G7} className="img_attribute1"/>
        Attribute
          
          <img src={G12} className="img_attribute1"/>
          </h1>
          
			<Container>
				<Col className='bounce-in-right'>
       
          
          <img src={p8} className="img_attribute"/>
              
        </Col>
				<Col>
					
					<h4>Each NFT is algorithmically generated by combining 170+ unique traits with varying rarity across categories.</h4>
          
				<Row>
        {/* 屬性有多少種 */}
        <Table striped bordered hover variant="dark">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>Types</th>
                        <th></th>
                        <th>Variations</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td></td>
                        <td>20</td>
                        <td>Total Robots</td>
                        <td>20</td>
                        <td>Head Tops</td>
                      </tr>
                      <tr>
                      <td></td>
                        <td>Common</td>
                        <td>Robotos</td>
                        <td>20</td>
                        <td>Eyes</td>
                        
                      </tr>
                      <tr>
                      <td></td>
                        <td>Less Common</td>
                        <td>Helmetos</td>
                        <td>10</td>
                        <td>Helmets</td>
                      
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>20</td>
                        <td>mouth</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>10</td>
                        <td>ears</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>10</td>
                        <td>Arms</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>5</td>
                        <td>backpack</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>5</td>
                        <td>body</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>3</td>
                        <td>Head Types</td>
                      </tr>
                      <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>20</td>
                        <td>equipment</td>
                      </tr>
                    </tbody>
          </Table>
          
				</Row>
        
				</Col>
				
			</Container>
			<div className='diva1'>
			  <br/>
			  	<a href='http://localhost:3000/Robot_Shop'>
                    <button className='button4'>Go to the shop ➝</button>
          </a>
			  	<br/>
				<strong className='text4'>STUST UNIVERSE ROBOTS</strong>
			</div>
      
      
		</div>
    </div>
	);
}

export default Attribute;